# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 2000
cpus_per_task: 10
gpus_per_node: 2  # ddp not currently supported
mem_gb: 200
name: ${hydra.job.name}
partition: inferno                      # Updated partition
account: "gts-rs275-paid"        # Added account
comment: null
constraint: null
